site_name: The Technical Collective
docs_dir: files/docs

theme:
  name: material
  logo: assets/img/tclogo.png        
  favicon: assets/img/favicon.png  # ← optional
  font:
    text: Inter
    code: "JetBrains Mono"
  palette:
    - scheme: default
      primary: indigo
      accent: cyan
    - scheme: slate
      primary: indigo
      accent: cyan
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.highlight
    - content.code.copy

plugins:
  - search
  - ezlinks
  - awesome-pages

extra_css:
  - assets/css/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
