site_name: The Technical Collective
docs_dir: files/docs

theme:
  name: material

plugins:
  - search
  - ezlinks
  - awesome-pages        # ← auto-nav plugin

# nav: block deleted – the plugin builds the sidebar from folders & files
