site_name: "The Technical Collective"    # Site title
docs_dir: files/docs
site_url: https://the-technical-collective.github.io/

theme:
  name: material

  # ── Branding ───────────────────────────────────────────────
  logo: assets/img/tclogo.png        # 32-160 px SVG / PNG
  favicon: assets/img/favicon.ico    # optional

  # ── Typeface ───────────────────────────────────────────────
  font:
    text: Inter
    code: "JetBrains Mono"

  # ── Colour palette ────────────────────────────────────────
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # ── UX & Navigation ───────────────────────────────────────
  features:
    - navigation.instant            # turbo-links
    - navigation.sections           # collapsible groups
    - navigation.expand             # sidebar open by default
    - navigation.tracking           # highlight current section in ToC
    - navigation.top                # add a 'back to top' button
    - search.highlight
    - content.code.copy

plugins:
  - search
  - ezlinks
  - awesome-pages                  # auto-builds sidebar

extra_css:
  - assets/css/extra.css           # universal tweaks

extra_javascript:
  - assets/js/sidebar.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji

# edit_uri: ""   # uncomment to remove "Edit on GitHub" links
