site_name: " "                       # required but invisible
docs_dir: files/docs
site_url: https://the-technical-collective.github.io/

theme:
  name: material

  # ── Branding ───────────────────────────────────────────────
  logo: assets/img/tclogo.png        # 32-160 px SVG / PNG
  favicon: assets/img/favicon.ico    # optional

  # ── Typeface ───────────────────────────────────────────────
  font:
    text: Inter
    code: "JetBrains Mono"

  # ── Colour palette ────────────────────────────────────────
  palette:
    - scheme: default
      primary: indigo
      accent: cyan
    - scheme: slate
      primary: indigo
      accent: cyan

  # ── UX & Navigation ───────────────────────────────────────
  features:
    - navigation.instant            # turbo-links
    - navigation.sections           # collapsible groups
    - navigation.expand             # sidebar open by default
    - search.highlight
    - content.code.copy

  # ── Hide the right-hand ToC completely ────────────────────
  hide:
    - toc

plugins:
  - search
  - ezlinks
  - awesome-pages                  # auto-builds sidebar

extra_css:
  - assets/css/extra.css           # universal tweaks

extra_javascript:
  - assets/js/sidebar.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji

# edit_uri: ""   # uncomment to remove “Edit on GitHub” links
